services:
  db:
    image: postgres:18.1-alpine
    container_name: axum-postgres
    env_file:
      - ./env_files/DB_ADMIN.env
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  axum-dev:
    depends_on:
      - db
    build:
      context: ./axum_project
      dockerfile: Dockerfile
    image: axum:dev
    container_name: axum-dev
    env_file:
      - ./env_files/DB_URL.env
      - ./env_files/DEV.env
    working_dir: /home/app
    volumes:
      - ./axum_project/axum-project:/home/app
      - /app/target
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8080:8000
    networks:
      - backend

# CMD ["cargo", "run", "--manifest-path", "./migration/Cargo.toml", "--", "up"]
  sea-orm-upper:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: sea-orm:dev
    profiles: ["migration-up"]
    container_name: sea-orm-upper
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "migrate", "up"]
    volumes:
      - ./db:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

# cargo run --manifest-path ./migration/Cargo.toml -- down -n 1
  sea-orm-downer:
    image: sea-orm:dev
    profiles: ["migration-downer"]
    container_name: sea-orm-downer
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "migrate", "down"]
    volumes:
      - ./db:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

  sea-orm-entity:
    image: sea-orm:dev
    profiles: ["generation-entity"]
    container_name: sea-orm-entity
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "generate", "entity", "-o", "src/entities", "--with-serde", "both"]
    volumes:
      - ./axum_project/axum-project:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

volumes:
  db-data:
    name: axum-postgres-db-data

networks:
  backend:
    name: axum-backend-network
    driver: bridge
