services:
  db:
    image: postgres:18.1-alpine
    container_name: axum-postgres
    env_file:
      - ./env_files/DB_ADMIN.env
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  axum-backend-dev:
    depends_on:
      - db
    build:
      context: ./axum_project
      dockerfile: Dockerfile.backend
    image: axum-backend:dev
    container_name: axum-backend-dev
    env_file:
      - ./env_files/DB_URL.env
      - ./env_files/DEV.env
    working_dir: /home/app
    # command: ["cargo", "watch", "-w", "backend", "-w", "shared","-x", "run", "--bin", "backend"]
    command: cargo watch -w backend -w shared -x "run --bin backend"
    volumes:
      - ./axum_project:/home/app
      - /home/app/target_docker
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    ports:
      - 8081:8000
    networks:
      - backend

  axum-client-dev:
    depends_on:
      - db
    build:
      context: ./axum_project
      dockerfile: Dockerfile.client
    image: axum-client:dev
    container_name: axum-client-dev
    env_file:
      - ./env_files/DB_URL.env
      - ./env_files/DEV.env
    working_dir: /home/app
    # 반응형으로 실행
    # docker compose attach axum-client-dev하면 됨
    stdin_open: true
    tty: true
    # command: cargo watch -w ssr -w shared -x "run --bin ssr"
    # command: cargo watch -w ssr -w shared -s "dx serve --server --package ssr --addr 0.0.0.0 --port 8001"
    command: dx serve --web --hotpatch --package client --addr 0.0.0.0 --port 8001
    volumes:
      - ./axum_project:/home/app
      - /home/app/target_docker
    ports:
      - 8080:8001
    networks:
      - backend

# CMD ["cargo", "run", "--manifest-path", "./migration/Cargo.toml", "--", "up"]
  sea-orm-upper:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: sea-orm:dev
    profiles: ["migration-up"]
    container_name: sea-orm-upper
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "migrate", "up"]
    volumes:
      - ./db:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

# cargo run --manifest-path ./migration/Cargo.toml -- down -n 1
  sea-orm-downer:
    image: sea-orm:dev
    profiles: ["migration-downer"]
    container_name: sea-orm-downer
    user: "${CURRENT_USER}"
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "migrate", "down"]
    volumes:
      - ./db:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

  sea-orm-entity:
    image: sea-orm:dev
    profiles: ["generation-entity"]
    container_name: sea-orm-entity
    user: "${CURRENT_USER}"
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    command: ["sea-orm-cli", "generate", "entity", "-o", "src/entities", "--with-serde", "both"]
    volumes:
      - ./axum_project/backend:/home/app
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

  sea-orm-cli:
    image: sea-orm:dev
    profiles: ["create_migrate"]
    container_name: sea-orm-entity
    user: "${CURRENT_USER}"
    env_file:
      - ./env_files/DB_URL.env
    working_dir: /home/app
    volumes:
      - ./db:/home/app
    command: ["sea-orm-cli", "migrate", "generate", "update"]
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend

volumes:
  db-data:
    name: axum-postgres-db-data

networks:
  backend:
    name: axum-backend-network
    driver: bridge
